### ISSUE TITLE
Just ONE residue allowed. 

### ISSUE THREAD

**Issue by kasonibare42** [leelasd/ligpargen#18]
Feature request

Hello LigPArGen Users and  @leelasd 

I am trying to generate some OPLS parameters for my structure. Yes. there are two residues quite right but why can't LigPArGen provide the parameters for this structure? Is there another way to do this. I can't attach the pdb file to this email because the editor doesn't support it.

**Comment by leelasd** [comment]
Can you email me the molecule or just drag and drop the PDB here. I will look into it

**Comment by kasonibare42** [comment]
Thank you very much, Leela


I have attached the molecule to this email.

________________________________

**Comment by kasonibare42** [comment]
Can you kindly send your email. I sent an email to leela.dodda@yale.edu but I'm not sure you got the email.

**Comment by leelasd** [comment]
I am closing the issue. Seems like this is resolved.

**Comment by kasonibare42** [comment]
This was not resolved. You said you were going to look into it but I never got feedback from you.

________________________________

**Comment by leelasd** [comment]
Yes !! Sorry my bad. 
@kasonibare42 
LigParGen doesn't support multiple residues as of now and the only solution is to just give one residue name in the PDB file and get the parameters.

**Comment by kasonibare42** [comment]
Thank you very much.

On Jun 26, 2018 12:48 PM, Leela Dodda <notifications@github.com> wrote:

Yes !! Sorry my bad.
@kasonibare42<https://github.com/kasonibare42>
LigParGen doesn't support multiple residues as of now and the only solution is to just give one residue name in the PDB file and get the parameters.
